---
# generated by https://github.com/hashicorp/terraform-plugin-docs
page_title: "st-alicloud_alidns_domain_attachment Resource - st-alicloud"
subcategory: ""
description: |-
  Provides a Alidns domain attachment resource.
---

# st-alicloud_alidns_domain_attachment (Resource)

Provides a Alidns domain attachment resource.

## Example Usage

```terraform
resource st-alicloud_alidns_domain_attachment "dns_attachment" {
	instance_id = "dns-sg-vfp37q58i0w"
	domain = "test.com"
}
```

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `domain` (String) Domain to bind to instance domain.
- `instance_id` (String) Instance Domain Id.
